using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.SignalR;
using SharpTalk.Shared.DTOs;
using System.Security.Claims;

namespace SharpTalk.Api.Hubs;

[Authorize]
public class ChatHub : Hub
{
    public async Task JoinChannel(int channelId)
    {
        await Groups.AddToGroupAsync(Context.ConnectionId, channelId.ToString());
    }

    public async Task LeaveChannel(int channelId)
    {
        await Groups.RemoveFromGroupAsync(Context.ConnectionId, channelId.ToString());
    }

    public async Task SendMessage(int channelId, string content)
    {
        var userId = int.Parse(Context.User?.FindFirst(ClaimTypes.NameIdentifier)?.Value!);
        var username = Context.User?.FindFirst(ClaimTypes.Name)?.Value ?? "Unknown";

        var messageDto = new MessageDto
        {
            Id = 0, // In-memory for now, or generated by DB
            ChannelId = channelId,
            UserId = userId,
            Username = username,
            Content = content,
            Timestamp = DateTime.UtcNow
        };

        // Broadcast to the channel group
        await Clients.Group(channelId.ToString()).SendAsync("ReceiveMessage", messageDto);
    }
}
